# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 15:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('an_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='originalmodel',  # Note: Not using CamelCase!
            new_name='renamedmodel',
        ),
    ]
